# Generated by Django 4.2.2 on 2023-06-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100, null=True)),
                ("Service_charge", models.CharField(max_length=100, null=True)),
                ("min_charge", models.CharField(max_length=100, null=True)),
                ("Avg_charge", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
