# Generated by Django 4.2.2 on 2023-06-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_prices"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100, null=True)),
                ("CP", models.CharField(max_length=100, null=True)),
                ("Service", models.CharField(max_length=100, null=True)),
                ("Delicious_level", models.CharField(max_length=100, null=True)),
                ("Clean", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Food_Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100, null=True)),
                ("Type", models.CharField(max_length=100, null=True)),
                ("Style", models.CharField(max_length=100, null=True)),
                ("Veg", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100, null=True)),
                ("Time", models.CharField(max_length=100, null=True)),
                ("Menu", models.CharField(max_length=100, null=True)),
                ("FB", models.CharField(max_length=100, null=True)),
                ("Phone", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
