# Generated by Django 4.2.2 on 2023-06-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0003_comment_food_type_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="Infos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100, null=True)),
                ("START_Time", models.TimeField()),
                ("Close_Time", models.TimeField()),
                ("Menu", models.CharField(max_length=100, null=True)),
                ("FB", models.CharField(max_length=100, null=True)),
                ("Phone", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Info",
        ),
    ]
