# Generated by Django 4.2.2 on 2023-06-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0004_infos_delete_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="Positions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100, null=True)),
                ("Area", models.CharField(max_length=100, null=True)),
                ("Road", models.CharField(max_length=100, null=True)),
                ("Door_num", models.CharField(max_length=100, null=True)),
                ("Floor", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Position",
        ),
    ]
